"""Add shortlists and discovery indexes

Revision ID: 34f9b29e33cf
Revises: 5600c2ae3f75
Create Date: 2026-03-14 15:26:27.127317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f9b29e33cf'
down_revision: Union[str, Sequence[str], None] = '5600c2ae3f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shortlist_user_asset', 'shortlists', ['user_id', 'media_asset_id'], unique=True)
    op.create_index('ix_media_asset_pricing_base_price', 'media_asset_pricing', ['base_price'], unique=False)
    op.create_index('ix_media_asset_regions_city', 'media_asset_regions', ['city'], unique=False)
    op.create_index('ix_media_assets_discovery_status', 'media_assets', ['status', 'visibility'], unique=False)
    op.create_index('ix_media_assets_search_category', 'media_assets', ['category'], unique=False)
    op.create_index('ix_media_assets_search_media_type', 'media_assets', ['media_type'], unique=False)
    op.create_index('ix_media_assets_search_title', 'media_assets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_assets_search_title', table_name='media_assets')
    op.drop_index('ix_media_assets_search_media_type', table_name='media_assets')
    op.drop_index('ix_media_assets_search_category', table_name='media_assets')
    op.drop_index('ix_media_assets_discovery_status', table_name='media_assets')
    op.drop_index('ix_media_asset_regions_city', table_name='media_asset_regions')
    op.drop_index('ix_media_asset_pricing_base_price', table_name='media_asset_pricing')
    op.drop_index('ix_shortlist_user_asset', table_name='shortlists')
    op.drop_table('shortlists')
    # ### end Alembic commands ###
