"""Add social_link to media_assets

Revision ID: 5600c2ae3f75
Revises: 576b1c5901e9
Create Date: 2026-03-14 14:26:22.015623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5600c2ae3f75'
down_revision: Union[str, Sequence[str], None] = '576b1c5901e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('social_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'social_link')
    # ### end Alembic commands ###
