"""Add Sprint 2 Inventory Models

Revision ID: 576b1c5901e9
Revises: 65aa77604960
Create Date: 2026-03-14 13:59:57.186831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576b1c5901e9'
down_revision: Union[str, Sequence[str], None] = '65aa77604960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_profile_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('public_slug', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_slug')
    )
    op.create_table('media_asset_audience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('total_reach', sa.Integer(), nullable=True),
    sa.Column('avg_views', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('male_percent', sa.Float(), nullable=True),
    sa.Column('female_percent', sa.Float(), nullable=True),
    sa.Column('age_13_17', sa.Float(), nullable=True),
    sa.Column('age_18_24', sa.Float(), nullable=True),
    sa.Column('age_25_34', sa.Float(), nullable=True),
    sa.Column('age_35_44', sa.Float(), nullable=True),
    sa.Column('age_45_plus', sa.Float(), nullable=True),
    sa.Column('top_cities', sa.JSON(), nullable=False),
    sa.Column('top_interests', sa.JSON(), nullable=False),
    sa.Column('audience_quality_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_table('media_asset_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_asset_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_asset_formats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('format_name', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('quantity_limit', sa.Integer(), nullable=True),
    sa.Column('creative_requirements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_asset_outdoor_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=64), nullable=True),
    sa.Column('screen_type', sa.String(length=64), nullable=True),
    sa.Column('daily_traffic_estimate', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Float(), nullable=True),
    sa.Column('illumination', sa.Boolean(), nullable=True),
    sa.Column('landmark_info', sa.Text(), nullable=True),
    sa.Column('facing_direction', sa.String(length=64), nullable=True),
    sa.Column('installation_type', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_table('media_asset_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_asset_social_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('avg_story_views', sa.Integer(), nullable=True),
    sa.Column('avg_post_views', sa.Integer(), nullable=True),
    sa.Column('avg_video_views', sa.Integer(), nullable=True),
    sa.Column('avg_comments', sa.Integer(), nullable=True),
    sa.Column('avg_shares', sa.Integer(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('authenticity_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_asset_id')
    )
    op.create_table('media_asset_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('format_id', sa.UUID(), nullable=True),
    sa.Column('pricing_model', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('min_order_value', sa.Float(), nullable=True),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['media_asset_formats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_asset_pricing')
    op.drop_table('media_asset_social_details')
    op.drop_table('media_asset_regions')
    op.drop_table('media_asset_outdoor_details')
    op.drop_table('media_asset_formats')
    op.drop_table('media_asset_files')
    op.drop_table('media_asset_availability')
    op.drop_table('media_asset_audience')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
